name: Test Build Micronaut

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -ppassword --silent; then
              echo "MySQL ready"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done
          exit 1

      - name: Gradle build
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Publish to Github packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: $${{ secrets.TOKEN }}